version: "2"
services:
  web:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  frontend:
    container_name: "frontend"
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
  backend:
    container_name: "backend"
    build: ./backend
    restart: unless-stopped
    ports:
      - "4000:4000"
  db:
    container_name: pg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - ./pgadmin:/var/lib/pgadmin

volumes:
  caddy_data:
  caddy_config:
